version: '3.3'
services:
  dashboard:
    container_name: dashboard
    build: ./dashboard
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start